---
# Role tasks

- block:
    - name: Activate Check_MK agent logwatch plugin
      copy:
        src: "{{ check_mk_agent_logwatch_available_plugins_dir }}/mk_logwatch"
        dest: "{{ check_mk_agent_logwatch_plugins_dir }}"
        remote_src: yes
        mode: 0755

    - name: Setup Check_MK agent logwatch config file
      template:
        src: logwatch.cfg.j2
        dest: "{{ check_mk_agent_logwatch_conf_path }}"
      vars:
        check_mk_agent_logwatch_to_manage: >-
          {{ check_mk_agent_logwatch
             + ((check_mk_agent_logwatch_load_from_hostvars)
                | ternary(check_mk_agent_logwatch_hostvars
                          | default([])
                          | flatten, [])) }}
  tags:
    - role::check_mk_agent_logwatch
    - role::check_mk_agent_logwatch::config
