---
# Role tasks

- block:
    - include_tasks: gather.yml

    - name: Install Check_MK agent logwatch plugin
      include_tasks: artifact.yml
      when: check_mk_agent_logwatch_artifact is defined

    - name: Setup Check_MK agent logwatch config file
      template:
        src: logwatch.cfg.j2
        dest: "{{ check_mk_agent_logwatch_config_dir }}/logwatch.cfg"
        mode: "{{ check_mk_agent_logwatch_config_mode }}"
      vars:
        check_mk_agent_logwatch_to_manage: >-
          {{ check_mk_agent_logwatch
             + ((check_mk_agent_logwatch_load_from_hostvars)
                | ternary(check_mk_agent_logwatch_hostvars
                          | default([])
                          | flatten, [])) }}
  tags:
    - role::check_mk_agent_logwatch
    - role::check_mk_agent_logwatch::config
